name: Release

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true
    - run: npm install --global release-it
    - run: release-it --ci --config .release-it-release.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
